/*
 * This source file was generated by the Gradle 'init' task
 */
package junior_research_project;

public class Main {
    public static void main(String[] args) {
        int numIterations = 100;

        Simulation simulation = new Simulation();
        simulation.runSimulation(numIterations);
    }
}
