/*
 * This source file was generated by the Gradle 'init' task
 */
package junior_research_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
